version: '3.3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: unity-java-docker-compose
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://unity-database-docker-compose:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - CUSTOM_HTTP_MAX_FILE_SIZE=9000MB
      - CUSTOM_HTTP_MAX_REQUEST_SIZE=9050MB
    volumes:
      - .\src\main\resources\videos:/app/src/main/resources/videos

  db:
    image: 'postgres:latest'
    container_name: unity-database-docker-compose
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - .\src\main\resources\database:/var/lib/postgresql/data